name: Update README
on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - .github/**
      - update-readme.js

jobs:
  update-readme:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"  # 커밋 메시지에 [skip ci]가 포함된 경우 실행 안 함
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        persist-credentials: false
        fetch-depth: 2  # 충분한 히스토리를 가져오기 위해 fetch-depth를 2로 설정

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: |
        echo '{}' > package.json
        npm install axios cheerio

    - name: Update README.md
      run: node update-readme.js

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.CODINGTEST_WORKFLOW_TOKEN }}
      run: |
        git config --global user.email "diehreo@gmail.com"
        git config --global user.name "mag123c"
        git remote set-url origin https://x-access-token:${{ secrets.CODINGTEST_WORKFLOW_TOKEN }}@github.com/${{ github.repository }}.git
        git add README.md
        git commit -m "Update README.md [skip ci]"
        git push origin HEAD:main
